// KeePass Standard Icons (0-68) mapped to Lucide React icons
// Based on official KDBX format specification and KeePass implementation
// Icons are stored in the icon_id field, NOT in tags

import {
  Key,
  Globe,
  AlertTriangle,
  Server,
  Clipboard,
  MessageSquare,
  Package,
  FileText,
  Plug,
  Contact,
  BookOpen,
  Camera,
  Wifi,
  KeyRound,
  Zap,
  ScanLine,
  Star,
  Disc,
  Monitor,
  Mail,
  Settings,
  ListTodo,
  FileType,
  MonitorCheck,
  Radio,
  Inbox,
  Save,
  Cloud,
  FileAudio,
  Terminal,
  HardDrive,
  Printer,
  PieChart,
  PlayCircle,
  Wrench,
  GlobeLock,
  Archive,
  Percent,
  Share2,
  Clock,
  Search,
  Spline,
  MemoryStick,
  Trash2,
  StickyNote,
  X,
  HelpCircle,
  Package as PackageBox,
  Folder,
  FolderOpen,
  FileArchive,
  LockOpen,
  Lock,
  CheckCircle,
  Pen,
  ImageIcon,
  BookUser,
  Table,
  KeySquare,
  Code,
  Home,
  StarOff,
  Bug,
  Apple,
  type LucideIcon,
} from "lucide-react";

export interface KeePassIcon {
  id: number;
  name: string;
  icon: LucideIcon;
  description: string;
}

// KeePass standard 69 icons (0-68) with Lucide equivalents
// Mapped according to official KDBX specification
export const KEEPASS_ICONS: KeePassIcon[] = [
  { id: 0, name: "Key", icon: Key, description: "Key / Password" },
  { id: 1, name: "World", icon: Globe, description: "Network / World" },
  { id: 2, name: "Warning", icon: AlertTriangle, description: "Warning" },
  { id: 3, name: "Server", icon: Server, description: "Server" },
  { id: 4, name: "MarkedDirectory", icon: Clipboard, description: "Clipboard / Notes" },
  { id: 5, name: "UserCommunication", icon: MessageSquare, description: "Language / Communication" },
  { id: 6, name: "Parts", icon: Package, description: "Blocks / Packages" },
  { id: 7, name: "Notepad", icon: FileText, description: "Text Editor" },
  { id: 8, name: "Socket", icon: Plug, description: "Network Socket" },
  { id: 9, name: "Identity", icon: Contact, description: "User Identity" },
  { id: 10, name: "AddressBook", icon: BookOpen, description: "Address Book" },
  { id: 11, name: "Camera", icon: Camera, description: "Camera / Pictures" },
  { id: 12, name: "IRCommunication", icon: Wifi, description: "Wireless Network" },
  { id: 13, name: "Keys", icon: KeyRound, description: "Keys / Keyring" },
  { id: 14, name: "Energy", icon: Zap, description: "Power / Energy" },
  { id: 15, name: "Scanner", icon: ScanLine, description: "Scanner" },
  { id: 16, name: "StarYellow", icon: Star, description: "Favorites / Bookmarks" },
  { id: 17, name: "CD", icon: Disc, description: "Optical Storage" },
  { id: 18, name: "Monitor", icon: Monitor, description: "Monitor / Display" },
  { id: 19, name: "EMail", icon: Mail, description: "Email / Letter" },
  { id: 20, name: "Configuration", icon: Settings, description: "Gears / Settings" },
  { id: 21, name: "ClipboardReady", icon: ListTodo, description: "Todo / Checklist" },
  { id: 22, name: "PaperNew", icon: FileType, description: "Empty Document" },
  { id: 23, name: "Screen", icon: MonitorCheck, description: "Computer Desktop" },
  { id: 24, name: "EMailBox", icon: Radio, description: "Remote Connection" },
  { id: 25, name: "Disk", icon: Inbox, description: "Email Inbox" },
  { id: 26, name: "Drive", icon: Save, description: "Floppy / Save" },
  { id: 27, name: "PaperReady", icon: Cloud, description: "Remote Storage" },
  { id: 28, name: "Folder", icon: FileAudio, description: "Media Files" },
  { id: 29, name: "FolderOpen", icon: LockOpen, description: "Secure Shell" },
  { id: 30, name: "FolderPackage", icon: Terminal, description: "Console / Terminal" },
  { id: 31, name: "LockOpen", icon: Printer, description: "Printer" },
  { id: 32, name: "PaperFlag", icon: PieChart, description: "Disk Utilization" },
  { id: 33, name: "PaperNew2", icon: PlayCircle, description: "Launch Program" },
  { id: 34, name: "Run", icon: Wrench, description: "Wrench / Settings" },
  { id: 35, name: "TerminalEncrypted", icon: GlobeLock, description: "Internet Computer" },
  { id: 36, name: "PaperFlag2", icon: Archive, description: "File Compression" },
  { id: 37, name: "Trash", icon: Percent, description: "Percentage" },
  { id: 38, name: "TuxImage", icon: Share2, description: "Windows Share" },
  { id: 39, name: "Clock", icon: Clock, description: "Time / Clock" },
  { id: 40, name: "SearchInPage", icon: Search, description: "Search / Magnifier" },
  { id: 41, name: "Vector", icon: Spline, description: "Vector Graphics" },
  { id: 42, name: "Memory", icon: MemoryStick, description: "Memory Hardware" },
  { id: 43, name: "TrashBin", icon: Trash2, description: "Recycle Bin" },
  { id: 44, name: "Note", icon: StickyNote, description: "Post-it Note" },
  { id: 45, name: "Cancel", icon: X, description: "Cancel / Red Cross" },
  { id: 46, name: "Help", icon: HelpCircle, description: "Help" },
  { id: 47, name: "Package", icon: PackageBox, description: "Software Package" },
  { id: 48, name: "Folder2", icon: Folder, description: "Closed Folder" },
  { id: 49, name: "FolderOpen2", icon: FolderOpen, description: "Open Folder" },
  { id: 50, name: "TARPackage", icon: FileArchive, description: "TAR Archive" },
  { id: 51, name: "Decrypted", icon: LockOpen, description: "Decryption" },
  { id: 52, name: "Encrypted", icon: Lock, description: "Encryption" },
  { id: 53, name: "Apply", icon: CheckCircle, description: "OK / Green Tick" },
  { id: 54, name: "Signature", icon: Pen, description: "Pen / Signature" },
  { id: 55, name: "Thumbnail", icon: ImageIcon, description: "Image Preview" },
  { id: 56, name: "AddressBook2", icon: BookUser, description: "Address Book" },
  { id: 57, name: "View", icon: Table, description: "Tabular Data" },
  { id: 58, name: "SecretKey", icon: KeySquare, description: "Private Key" },
  { id: 59, name: "MultiKeys", icon: Code, description: "Software Development" },
  { id: 60, name: "Home", icon: Home, description: "Home Folder" },
  { id: 61, name: "Star2", icon: StarOff, description: "Favorites / Star" },
  { id: 62, name: "Penguin", icon: Bug, description: "Tux / Linux" },
  { id: 63, name: "Feather", icon: Star, description: "Feather / Apache" },
  { id: 64, name: "Apple", icon: Apple, description: "Apple / macOS" },
  { id: 65, name: "Wiki", icon: BookOpen, description: "Wikipedia" },
  { id: 66, name: "Money", icon: Star, description: "Money / Finances" },
  { id: 67, name: "Certificate", icon: FileType, description: "Digital Certificate" },
  { id: 68, name: "Mobile", icon: Monitor, description: "Mobile Device" },
];

// Helper function to get icon by ID
export function getIconById(id: number): KeePassIcon {
  const icon = KEEPASS_ICONS.find((i) => i.id === id);
  return icon || KEEPASS_ICONS[0]; // Default to Key if not found
}

// Helper function to get icon component by ID
export function getIconComponentById(id: number): LucideIcon {
  return getIconById(id).icon;
}
